# -*- coding: utf-8 -*-
"""fetching_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bU1GAWV9tvVb25zI-O6aB96oPRjmL-G6
"""

import requests

API_KEY = ""

SEARCH_URL = "https://www.googleapis.com/youtube/v3/search"
VIDEO_URL = "https://www.googleapis.com/youtube/v3/videos"

def search_videos(query, region_code="ID", max_results=50):
    video_ids = []
    next_page_token = None

    while len(video_ids) < max_results:
        params = {
            "part": "snippet",
            "q": query,
            "type": "video",
            "maxResults": 50,
            "regionCode": region_code,
            "pageToken": next_page_token,
            "key": API_KEY
        }

        response = requests.get(SEARCH_URL, params=params)
        data = response.json()

        for item in data.get("items", []):
            vid = item["id"]["videoId"]
            if vid not in video_ids:  # hindari duplikat
                video_ids.append(vid)

        next_page_token = data.get("nextPageToken")

        if not next_page_token:
            break

    return video_ids[:max_results]

def get_video_details(video_ids):
    results = []

    # batching (max 50 per request)
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]

        params = {
            "part": "snippet,statistics,contentDetails",
            "id": ",".join(batch_ids),
            "key": API_KEY
        }

        response = requests.get(VIDEO_URL, params=params)
        data = response.json()

        for item in data.get("items", []):
            results.append({
                "videoId": item["id"],
                "title": item["snippet"]["title"],
                "channel": item["snippet"]["channelTitle"],
                "views": int(item["statistics"].get("viewCount", 0)),
                "likes": int(item["statistics"].get("likeCount", 0)),
                "comments": int(item["statistics"].get("commentCount", 0)),
                "publishedAt": item["snippet"]["publishedAt"],
                "duration": item["contentDetails"].get("duration", "P0D"),
                "region": params.get("regionCode", "Unknown")  # optional
            })

    return results

def build_dataset(query, region_code="ID", max_results=50):
    # 1. search video
    video_ids = search_videos(query, region_code, max_results)

    # 2. get details
    video_data = get_video_details(video_ids)

    return video_data

"""keywords = [
    # direct
    "how to stop brainrot",
    "mengatasi brainrot",
    
    # related
    "digital detox",
    "reduce screen time",
    "stop scrolling addiction",
    "doom scrolling",
    
    # indirect
    "dopamine detox",
    "how to focus better",
    "productivity tips",
    
    # indo
    "cara berhenti scrolling",
    "mengurangi screen time"
]
"""

# building data using 1 keyword and 1 region
data = build_dataset(
    query="mengatasi brainrot",
    region_code="ID",
    max_results=500
)

for d in data:
    print(f'Total data: {len(d)}')
    print(d)

# building data using more than one keyword and region
keywords = [
    # direct
    "how to stop brainrot",
    "mengatasi brainrot",

    # related
    "digital detox",
    "reduce screen time",
    "stop scrolling addiction",
    "doom scrolling"
]
regions = ["ID", "MY", "SG", "BN"]

all_data = []

for kw in keywords:
    for reg in regions:
        data = build_dataset(
            query=kw,
            region_code=reg,
            max_results=1000
        )
        all_data.extend(data)

print(len(all_data))

import json
import os

def save_to_json(data, filename="data/brainrot464.json"):
    # pastikan folder ada
    os.makedirs(os.path.dirname(filename), exist_ok=True)

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

    print(f"Data successfully saved to {filename}")

save_to_json(data)

import csv
import os

def save_to_csv(data, filename="data/brainrot464.csv"):
    # pastikan folder ada
    os.makedirs(os.path.dirname(filename), exist_ok=True)

    if len(data) == 0:
        print("No data to save")
        return

    keys = data[0].keys()

    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(data)

    print(f"Data successfully saved to {filename}")

save_to_csv(data)